name: Preparant per producció
run-name: ${{ github.actor }} està pujant npm ci (o install) i després el run build 🚀
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Instal·lar dependències i construir
        run: |
          cd ./my-project/
          npm install
          npm run build

      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          echo "Action desplegant a produccio" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./my-project/dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a19galdelred/web/actions2.a19galdelred.daw.inspedralbes.cat/public_html/web/
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
